# Generated by Django 2.2.12 on 2021-10-14 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('serialNumber', models.CharField(max_length=200)),
                ('originalOutputVoltage', models.FloatField()),
                ('dateOfPurchase', models.DateField()),
                ('capacity', models.CharField(max_length=10)),
                ('batteryType', models.CharField(max_length=200)),
                ('batteryDimensions', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
                ('terminalLayout', models.CharField(max_length=200)),
                ('warranty', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='UserBatteryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battery_sentry.Battery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battery_sentry.User')),
            ],
        ),
        migrations.CreateModel(
            name='DepletionReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depletionVoltageReading', models.FloatField()),
                ('readingDateTime', models.DateTimeField()),
                ('batteryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battery_sentry.Battery')),
            ],
        ),
        migrations.CreateModel(
            name='ChargeReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chargeVoltageReading', models.FloatField()),
                ('readingDateTime', models.DateTimeField()),
                ('batteryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battery_sentry.Battery')),
            ],
        ),
        migrations.AddField(
            model_name='battery',
            name='users',
            field=models.ManyToManyField(through='battery_sentry.UserBatteryDetail', to='battery_sentry.User'),
        ),
    ]
